name: gg_tree
description: gg_tree organizes data in a tree and allows to search or reference other tree items
version: 1.0.5
repository: https://github.com/ggsuite/gg_tree.git

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  path: ^1.8.0
  json_annotation: ^4.10.0
  gg_json: ^3.0.6

dev_dependencies:
  build_runner: ^2.4.6
  gg_golden: ^3.0.0
  gg_test_matchers: ^1.1.0
  json_serializable: ^6.6.1
  lints: ^6.0.0
  test: ^1.24.0